In [75]:
#Import All Libraries 
import numpy as np
import seaborn as sns
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier

In [76]:
df = pd.read_csv("heart.csv")                               #Read CSV File 
df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [77]:
y = df.HeartDisease
y

0      0
1      1
2      0
3      1
4      0
      ..
913    1
914    1
915    1
916    1
917    0
Name: HeartDisease, Length: 918, dtype: int64

In [78]:
X = df.drop('HeartDisease', axis=1)                             #Drop the Labels of The Dataset
X

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up
...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up

In [79]:
#Use label Encoder to Conver The String Data To Int
le_Sex = LabelEncoder()
le_ChestPainType = LabelEncoder()
le_RestingECG = LabelEncoder()
le_ExerciseAngina = LabelEncoder()
le_ST_Slope = LabelEncoder()

In [80]:
X['new_sex'] = le_Sex.fit_transform(X['Sex'])
X['new_ChestPainType'] = le_ChestPainType.fit_transform(X['ChestPainType'])
X['new_RestingECG'] = le_RestingECG.fit_transform(X['RestingECG'])
X['new_ExerciseAngina'] = le_ExerciseAngina.fit_transform(X['ExerciseAngina'])
X['new_ST_Slope'] = le_ST_Slope.fit_transform(X["ST_Slope"])

In [81]:
X

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,new_sex,new_ChestPainType,new_RestingECG,new_ExerciseAngina,new_ST_Slope
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,1,1,1,0,2
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,0,2,1,0,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,1,1,2,0,2
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,0,0,1,1,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,1,2,1,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1,3,1,0,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1,0,1,0,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1,0,1,1,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,0,1,0,0,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,1,2,1,0,2

In [82]:
X = X.drop(['Sex','ChestPainType','RestingECG','ExerciseAngina','ST_Slope'], axis=1)
X

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,new_sex,new_ChestPainType,new_RestingECG,new_ExerciseAngina,new_ST_Slope
0,40,140,289,0,172,0.0,1,1,1,0,2
1,49,160,180,0,156,1.0,0,2,1,0,1
2,37,130,283,0,98,0.0,1,1,2,0,2
3,48,138,214,0,108,1.5,0,0,1,1,1
4,54,150,195,0,122,0.0,1,2,1,0,2
...,...,...,...,...,...,...,...,...,...,...,...
913,45,110,264,0,132,1.2,1,3,1,0,1
914,68,144,193,1,141,3.4,1,0,1,0,1
915,57,130,131,0,115,1.2,1,0,1,1,1
916,57,130,236,0,174,0.0,0,1,0,0,1
917,38,138,175,0,173,0.0,1,2,1,0,2

In [83]:
X_train,X_test,y_train,y_test = train_test_split(X.values, y, test_size=0.1)

In [84]:
print(len(X_train))
print(len(X_test))
print(len(y_train))
print(len(y_test))

826
92
826
92

In [85]:

model = RandomForestClassifier()
model.fit(X_train,y_train)

RandomForestClassifier()

In [91]:
model.score(X_test,y_test)

0.8695652173913043

In [96]:
model.predict([[227, 230, 332, 0, 298, 0.0, 2219, 21, 2233, 0, 22]])

array([1], dtype=int64)

In [98]:
if model.predict([[227, 230, 332, 0, 298, 0.0, 2219, 21, 2233, 0, 22]])[0] == 1:
 print("Having heart disease")
else:
 print("Not having heart disease")

Having heart disease